SET DEFINE OFF;
CREATE TABLE D_CONTACT
(
  CUSTOMER_ID            NUMBER(12),
  ADDRESSID              NUMBER(12),
  CUSTOMER_TYPE          VARCHAR2(20 BYTE),
  MRKCONTACTS_PROFILE    VARCHAR2(50 BYTE),
  MRKCONTACTS_COMMENT    VARCHAR2(1000 BYTE),
  DEFAULTBRAND           VARCHAR2(50 BYTE),
  TAXID                  VARCHAR2(20 BYTE),
  GSTPER                 VARCHAR2(10 BYTE),
  QCURRENCY              VARCHAR2(3 BYTE),
  PHONE                  VARCHAR2(30 BYTE),
  PHONE_EXT              VARCHAR2(10 BYTE),
  MOBILE_PHONE           VARCHAR2(30 BYTE),
  FAX                    VARCHAR2(30 BYTE),
  EMAIL                  VARCHAR2(50 BYTE),
  TERRITORY              VARCHAR2(50 BYTE),
  STATUS                 VARCHAR2(10 BYTE),
  ORIGIN                 VARCHAR2(255 BYTE),
  LAST_NAME              VARCHAR2(50 BYTE),
  FIRST_NAME             VARCHAR2(50 BYTE),
  CARE_OF                VARCHAR2(250 BYTE),
  HOUSEHOLD_NAME         VARCHAR2(250 BYTE),
  GENDER                 VARCHAR2(1 BYTE),
  TITLE                  VARCHAR2(50 BYTE),
  MRKCONTACTS_BROADCAST  VARCHAR2(1 BYTE),
  MAIL_BROADCAST         VARCHAR2(1 BYTE),
  CUSTOMERID             VARCHAR2(15 BYTE),
  USEOK                  VARCHAR2(1 BYTE),
  COPYOK                 VARCHAR2(1 BYTE),
  MANAGEOK               VARCHAR2(1 BYTE),
  BIRTHDATE              DATE,
  BIRTHPLACE             VARCHAR2(50 BYTE),
  AGE                    NUMBER(4),
  PASSPORT_NUMBER        VARCHAR2(50 BYTE),
  PASSPORT_EXPIRATION    VARCHAR2(30 BYTE),
  PASSPORT_AUTHORITY     VARCHAR2(200 BYTE),
  PASSPORT_ISSUE_DATE    VARCHAR2(30 BYTE),
  NATIONALITY            VARCHAR2(50 BYTE),
  PAX_TYPE               VARCHAR2(3 BYTE),
  EMERGENCY_CONTACT      VARCHAR2(100 BYTE),
  EMERGENCY_PHONE        VARCHAR2(30 BYTE),
  CREATED_BY             VARCHAR2(50 BYTE),
  CREATED_DATE           DATE,
  WHOSTAMP               VARCHAR2(50 BYTE),
  DATESTAMP              DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX D_CONTACT_PK ON D_CONTACT
(CUSTOMER_ID)
LOGGING
TABLESPACE DTW_ADV_TABLES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE D_CONTACT ADD (
  CONSTRAINT D_CONTACT_PK
  PRIMARY KEY
  (CUSTOMER_ID)
  USING INDEX D_CONTACT_PK
  ENABLE VALIDATE);
