SET DEFINE OFF;
CREATE TABLE D_PRODUCT_DETAIL
(
  REFERENCE_NUMBER  NUMBER(38),
  PRODUCT_CODE      VARCHAR2(50 BYTE),
  PD_SEQUENCE       NUMBER(4),
  I_SEQ             NUMBER(4),
  REC_TYPE          VARCHAR2(1 BYTE),
  ITEM_ROLE         VARCHAR2(10 BYTE),
  SUPPLIER_ID       VARCHAR2(50 BYTE),
  SERVICE_ID        VARCHAR2(50 BYTE),
  DESCRIPTION       VARCHAR2(300 BYTE),
  FROM_DATE         DATE,
  TO_DATE           DATE,
  WEEK_DAYS         VARCHAR2(10 BYTE),
  ON_DAY            VARCHAR2(3 BYTE),
  ON_TIME           VARCHAR2(5 BYTE),
  DURATION          NUMBER(4),
  FLEX_DURATION     VARCHAR2(1 BYTE),
  MIN_NIGHTS        NUMBER(4),
  LINK_CODE         VARCHAR2(20 BYTE),
  AUTO_SELECT       VARCHAR2(10 BYTE),
  DIVISIBLE_PAX     NUMBER(4),
  INVOICE_FLAG      VARCHAR2(1 BYTE),
  ADDITIONAL_DATA   VARCHAR2(2000 BYTE),
  WHOSTAMP          VARCHAR2(100 BYTE),
  DATESTAMP         DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX D_PRODUCT_DETAIL_PK ON D_PRODUCT_DETAIL
(REFERENCE_NUMBER)
LOGGING
TABLESPACE DTW_ADV_TABLES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PRODTL_PRODCODE ON D_PRODUCT_DETAIL
(PRODUCT_CODE)
LOGGING
TABLESPACE DTW_ADV_TABLES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE D_PRODUCT_DETAIL ADD (
  CONSTRAINT D_PRODUCT_DETAIL_PK
  PRIMARY KEY
  (REFERENCE_NUMBER)
  USING INDEX D_PRODUCT_DETAIL_PK
  ENABLE VALIDATE);
