SET DEFINE OFF;
CREATE TABLE L_ACCCOMPANIES
(
  COMPANYID               VARCHAR2(10 BYTE),
  COMPANYNAME             VARCHAR2(30 BYTE),
  ADDRESS1                VARCHAR2(30 BYTE),
  ADDRESS2                VARCHAR2(30 BYTE),
  ADDRESS3                VARCHAR2(30 BYTE),
  CONTACT                 VARCHAR2(30 BYTE),
  PHONE                   VARCHAR2(20 BYTE),
  FAX                     VARCHAR2(20 BYTE),
  EMAIL                   VARCHAR2(50 BYTE),
  OPSFAX                  VARCHAR2(20 BYTE),
  OPSEMAIL                VARCHAR2(50 BYTE),
  ACCTFAX                 VARCHAR2(20 BYTE),
  ACCTEMAIL               VARCHAR2(50 BYTE),
  MARKFAX                 VARCHAR2(20 BYTE),
  MARKEMAIL               VARCHAR2(50 BYTE),
  GLDEPOSITS              VARCHAR2(15 BYTE),
  GLDEPOSITSNAME          VARCHAR2(85 BYTE),
  GLDEPOSITSTYPE          VARCHAR2(1 BYTE),
  GLAR                    VARCHAR2(15 BYTE),
  GLARNAME                VARCHAR2(85 BYTE),
  GLARTYPE                VARCHAR2(1 BYTE),
  GLPRIORPERREFUND        VARCHAR2(15 BYTE),
  GLPRIORPERREFUNDNAME    VARCHAR2(85 BYTE),
  GLPRIORPERREFUNDTYPE    VARCHAR2(1 BYTE),
  GLPREPAIDLANDCOST       VARCHAR2(15 BYTE),
  GLPREPAIDLANDCOSTNAME   VARCHAR2(85 BYTE),
  GLPREPAIDLANDCOSTTYPE   VARCHAR2(1 BYTE),
  GLPREPAIDAIRCOST        VARCHAR2(15 BYTE),
  GLPREPAIDAIRCOSTNAME    VARCHAR2(85 BYTE),
  GLPREPAIDAIRCOSTTYPE    VARCHAR2(1 BYTE),
  GLCONTLIABILITY         VARCHAR2(15 BYTE),
  GLCONTLIABILITYNAME     VARCHAR2(85 BYTE),
  GLCONTLIABILITYTYPE     VARCHAR2(1 BYTE),
  GLINCOMESUMMARY         VARCHAR2(15 BYTE),
  GLINCOMESUMMARYNAME     VARCHAR2(85 BYTE),
  GLINCOMESUMMARYTYPE     VARCHAR2(1 BYTE),
  GLRETAINEDEARNINGS      VARCHAR2(15 BYTE),
  GLRETAINEDEARNINGSNAME  VARCHAR2(30 BYTE),
  GLRETAINEDEARNINGSTYPE  VARCHAR2(1 BYTE),
  GLFXLIABILITY           VARCHAR2(15 BYTE),
  GLFXLIABILITYNAME       VARCHAR2(85 BYTE),
  GLFXLIABILITYTYPE       VARCHAR2(1 BYTE),
  GLFXINCOME              VARCHAR2(15 BYTE),
  GLFXINCOMENAME          VARCHAR2(85 BYTE),
  GLFXINCOMETYPE          VARCHAR2(1 BYTE),
  GLDEFERREDMEMBER        VARCHAR2(15 BYTE),
  GLDEFERREDMEMBERNAME    VARCHAR2(85 BYTE),
  GLDEFERREDMEMBERTYPE    VARCHAR2(1 BYTE),
  MOVEJOURNALID           VARCHAR2(15 BYTE),
  MOVEJOURNALNAME         VARCHAR2(30 BYTE),
  FISCALPERIOD            NUMBER(2),
  LASTCLOSE               VARCHAR2(10 BYTE),
  BASECURRENCY            VARCHAR2(3 BYTE),
  WHOSTAMP                VARCHAR2(50 BYTE),
  DATESTAMP               DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
