SET DEFINE OFF;
CREATE TABLE L_ACCTRANSDETAIL
(
  TRANSNUMBER        NUMBER(18),
  LEGNUM             NUMBER(10),
  GLNUM              VARCHAR2(20 BYTE),
  GLNAME             VARCHAR2(85 BYTE),
  AFFECTONGL         VARCHAR2(1 BYTE),
  LOCALAMOUNTDETAIL  NUMBER(18,2),
  BASEAMOUNTDETAIL   NUMBER(18,2),
  REFERENCE          VARCHAR2(50 BYTE),
  CLEARED            VARCHAR2(1 BYTE),
  CLEAREDPERIOD      NUMBER(10)
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
