SET DEFINE OFF;
CREATE TABLE L_ACCTRANS
(
  TRANSNUMBER       NUMBER(15),
  COMPANYID         VARCHAR2(15 BYTE),
  JOURNALID         VARCHAR2(15 BYTE),
  JOURNALNAME       VARCHAR2(80 BYTE),
  JOURNALTYPE       VARCHAR2(1 BYTE),
  TRANSDATE         DATE,
  TRANSSTATUS       VARCHAR2(1 BYTE),
  REFNUM            VARCHAR2(150 BYTE),
  INVOICEDATE       DATE,
  TCURRENCY         VARCHAR2(3 BYTE),
  EXCHRATE          NUMBER(8),
  LOCALAMOUNT       NUMBER(9),
  BASEAMOUNT        NUMBER(9),
  RESNUMBER         NUMBER(9),
  TRANSTYPE         VARCHAR2(2 BYTE),
  APPLYLOCAL        NUMBER(9),
  APPLYBASE         NUMBER(9),
  SOURCEID          VARCHAR2(15 BYTE),
  SOURCENAME        VARCHAR2(100 BYTE),
  SOURCETYPE        VARCHAR2(5 BYTE),
  PAYTO             VARCHAR2(50 BYTE),
  DESCRIPTION       VARCHAR2(4000 BYTE),
  PROCESSEDBYTRANS  NUMBER(9),
  PROCESSEDBYCHECK  VARCHAR2(25 BYTE),
  DUEDATE           DATE,
  TKTFARE           NUMBER(9),
  TKTTAX            NUMBER(9),
  TKTCOMMPER        NUMBER(9),
  TKTCOMMAMT        NUMBER(9),
  CONTRACTEDFOR     VARCHAR2(10 BYTE),
  WHOSTAMP          VARCHAR2(50 BYTE),
  DATESTAMP         DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
