SET DEFINE OFF;
CREATE TABLE L_EMPLOYEE_INFORMATION
(
  FIRSTNAME         VARCHAR2(50 BYTE),
  LASTNAME          VARCHAR2(50 BYTE),
  BIRTHDATE         DATE,
  HIREDATE          DATE,
  GENDER            VARCHAR2(10 BYTE),
  MANAGER           VARCHAR2(50 BYTE),
  DEPARTMENT        VARCHAR2(50 BYTE),
  SOFTTRIPUSERNAME  VARCHAR2(50 BYTE)
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
