SET DEFINE OFF;
CREATE TABLE L_INVENTORY
(
  BLOCKCODE     VARCHAR2(50 BYTE)               NOT NULL,
  IDATE         DATE                            NOT NULL,
  CONTRACTED    INTEGER,
  ALLOTTED      INTEGER,
  AVAILABLE     INTEGER,
  STATE         VARCHAR2(1 BYTE),
  RELEASEDAY    INTEGER,
  RSTATE        VARCHAR2(1 BYTE),
  ASSETID       VARCHAR2(25 BYTE),
  SHARES        VARCHAR2(30 BYTE),
  BLOCKCAP      INTEGER,
  BLOCKCAPTYPE  VARCHAR2(10 BYTE)
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
