SET DEFINE OFF;
CREATE TABLE L_MRKTERRITORY
(
  TERRITORYID           VARCHAR2(15 BYTE),
  TERRITORYDESCRIPTION  VARCHAR2(255 BYTE),
  BEGPOSTALCODE         VARCHAR2(9 BYTE),
  ENDPOSTALCODE         VARCHAR2(9 BYTE),
  COUNTRIES             VARCHAR2(100 BYTE),
  WHOSTAMP              VARCHAR2(50 BYTE),
  DATESTAMP             DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
