SET DEFINE OFF;
CREATE TABLE L_MRKCONTACTS
(
  CONTACTID              NUMBER(12),
  LASTNAME               VARCHAR2(50 BYTE),
  FIRSTNAME              VARCHAR2(50 BYTE),
  CAREOF                 VARCHAR2(250 BYTE),
  ADDRESSID              NUMBER(12),
  HOUSEHOLDNAME          VARCHAR2(250 BYTE),
  GENDER                 VARCHAR2(1 BYTE),
  TITLE                  VARCHAR2(50 BYTE),
  EMAIL                  VARCHAR2(50 BYTE),
  PHONE                  VARCHAR2(30 BYTE),
  PHONEEXT               VARCHAR2(10 BYTE),
  MOBILEPHONE            VARCHAR2(30 BYTE),
  FAX                    VARCHAR2(30 BYTE),
  MRKCONTACTS_BROADCAST  VARCHAR2(1 BYTE),
  MAILBROADCAST          VARCHAR2(1 BYTE),
  CONTACTTYPE            VARCHAR2(20 BYTE),
  MRKCONTACTS_PROFILE    VARCHAR2(50 BYTE),
  COMMCODE               VARCHAR2(20 BYTE),
  TERRITORY              VARCHAR2(50 BYTE),
  STATUS                 VARCHAR2(10 BYTE),
  ORIGIN                 VARCHAR2(255 BYTE),
  TAXID                  VARCHAR2(20 BYTE),
  GSTPER                 VARCHAR2(10 BYTE),
  QCURRENCY              VARCHAR2(3 BYTE),
  DEFAULTBRAND           VARCHAR2(50 BYTE),
  MRKCONTACTS_PASSWORD   VARCHAR2(20 BYTE),
  HINT                   VARCHAR2(30 BYTE),
  MRKCONTACTS_COMMENT    VARCHAR2(1000 BYTE),
  CUSTOMERID             VARCHAR2(15 BYTE),
  USEOK                  VARCHAR2(1 BYTE),
  COPYOK                 VARCHAR2(1 BYTE),
  MANAGEOK               VARCHAR2(1 BYTE),
  BIRTHDATE              DATE,
  BIRTHPLACE             VARCHAR2(50 BYTE),
  AGE                    NUMBER(4),
  PASSPORTNUMBER         VARCHAR2(50 BYTE),
  PASSPORTEXPIRATION     VARCHAR2(30 BYTE),
  PASSPORTAUTHORITY      VARCHAR2(200 BYTE),
  PASSPORTISSUEDATE      VARCHAR2(30 BYTE),
  NATIONALITY            VARCHAR2(50 BYTE),
  PAXTYPE                VARCHAR2(3 BYTE),
  EMERGENCYCONTACT       VARCHAR2(100 BYTE),
  EMERGENCYPHONE         VARCHAR2(30 BYTE),
  ADDITIONALDATA         VARCHAR2(4000 BYTE),
  CREATEDBY              VARCHAR2(50 BYTE),
  CREATEDDATE            DATE,
  WHOSTAMP               VARCHAR2(50 BYTE),
  DATESTAMP              DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
