SET DEFINE OFF;
CREATE TABLE L_MRKSUBSCRIPTIONLISTS
(
  LISTID            VARCHAR2(20 BYTE),
  LISTTYPE          VARCHAR2(20 BYTE),
  DESCRIPTION       VARCHAR2(75 BYTE),
  DISPLAYSEQ        NUMBER(9),
  DISPLAYTEXT       VARCHAR2(90 BYTE),
  BRANDID           VARCHAR2(100 BYTE),
  AFFILIATIONID     VARCHAR2(20 BYTE),
  SHOWNONSIGNUP     VARCHAR2(1 BYTE),
  SELECTEDONSIGNUP  VARCHAR2(1 BYTE),
  ADDITIONALDATA    VARCHAR2(1000 BYTE),
  WHOSTAMP          VARCHAR2(50 BYTE),
  DATESTAMP         DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
