SET DEFINE OFF;
CREATE TABLE L_MRKCONTACTPROMOTIONS
(
  CONTPROMOID     NUMBER(4),
  CONTACTID       VARCHAR2(20 BYTE),
  PROMOTIONID     VARCHAR2(20 BYTE),
  BOOKDATE        DATE,
  PRICE           NUMBER(9),
  BEGBOOK         DATE,
  ENDBOOK         DATE,
  STATUS          VARCHAR2(50 BYTE),
  ADDITIONALDATA  VARCHAR2(2000 BYTE),
  WHOSTAMP        VARCHAR2(50 BYTE),
  DATESTAMP       DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
