SET DEFINE OFF;
CREATE TABLE L_PRODUCT
(
  PRODUCTCODE         VARCHAR2(50 BYTE),
  PRODUCTNAME         VARCHAR2(250 BYTE),
  DESCRIPTION         VARCHAR2(1024 BYTE),
  BEGDATE             DATE,
  ENDDATE             DATE,
  BEGBDATE            DATE,
  ENDBDATE            DATE,
  DEFAULTMARKET       VARCHAR2(20 BYTE),
  PRODUCTTYPE         VARCHAR2(3 BYTE),
  NUMDAYS             NUMBER(4),
  DATESPECIFIC        VARCHAR2(1 BYTE),
  ROLLUPAIRALLOW      VARCHAR2(1 BYTE),
  SHAREOK             VARCHAR2(20 BYTE),
  LANDONLYOK          VARCHAR2(1 BYTE),
  AIRINCLUDED         VARCHAR2(1 BYTE),
  AIRMESSAGE          VARCHAR2(100 BYTE),
  AIRINFO             VARCHAR2(1000 BYTE),
  AIRCITIES           VARCHAR2(500 BYTE),
  EXTENSIONRULE       VARCHAR2(80 BYTE),
  PREPACKAGECODE      VARCHAR2(200 BYTE),
  POSTPACKAGECODE     VARCHAR2(200 BYTE),
  OPTIONSCODE         VARCHAR2(800 BYTE),
  TOUID               VARCHAR2(50 BYTE),
  TOUROFFSET          VARCHAR2(10 BYTE),
  DISTRIBUTEFREECOST  VARCHAR2(1 BYTE),
  FREERULE            VARCHAR2(300 BYTE),
  ACTIVEPAXRANGE      VARCHAR2(10 BYTE),
  SEARCHBY            VARCHAR2(800 BYTE),
  PRODUCTSTATUS       VARCHAR2(30 BYTE),
  ADDITIONALDATA      VARCHAR2(4000 BYTE),
  TRACKCHANGES        VARCHAR2(1 BYTE),
  ACTIVEASOF          DATE,
  CREATEDBY           VARCHAR2(50 BYTE),
  CREATEDDATE         DATE,
  WHOSTAMP            VARCHAR2(50 BYTE),
  DATESTAMP           DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
