SET DEFINE OFF;
CREATE TABLE L_PRODUCTPRICES
(
  PRODUCTCODE       VARCHAR2(50 BYTE)           NOT NULL,
  SEQ               INTEGER                     NOT NULL,
  BRANDID           VARCHAR2(100 BYTE),
  SELLMETHOD        VARCHAR2(20 BYTE),
  QCURRENCY         VARCHAR2(3 BYTE),
  SUPPLIERID        VARCHAR2(50 BYTE),
  SERVICEID         VARCHAR2(50 BYTE),
  SALESTATUS        VARCHAR2(20 BYTE),
  MATCHREQMASK      VARCHAR2(1 BYTE),
  MASK              VARCHAR2(20 BYTE),
  PAXRANGE          VARCHAR2(10 BYTE),
  DURATION          INTEGER,
  BEGINDDATE        DATE,
  ENDDDATE          DATE,
  BEGINBDATE        DATE,
  ENDBDATE          DATE,
  WEEKDAY           VARCHAR2(7 BYTE),
  FPTYPE            VARCHAR2(50 BYTE),
  USEDURATION       CHAR(1 BYTE),
  FROMADTPRICE      NUMBER(18,2),
  TOADTPRICE        NUMBER(18,2),
  ADTPRICE          NUMBER(18,2),
  ADTTAX            NUMBER(18,2),
  ADTGST            NUMBER(18,2),
  CHDPRICE          NUMBER(18,2),
  CHDTAX            NUMBER(18,2),
  CHDGST            NUMBER(18,2),
  ADDPAXPRICE       NUMBER(18,2),
  AIRADTALLOW       NUMBER(18,2),
  AIRCHDALLOW       NUMBER(18,2),
  INNERAIRADTALLOW  NUMBER(18,2),
  INNERAIRCHDALLOW  NUMBER(18,2),
  LANDCOST          NUMBER(18,2),
  AIRCOST           NUMBER(18,2),
  DISPLAYSTATUS     VARCHAR2(20 BYTE),
  ADDITIONALDATA    VARCHAR2(1000 BYTE),
  WHOSTAMP          VARCHAR2(50 BYTE),
  DATESTAMP         DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
