SET DEFINE OFF;
CREATE TABLE L_PRODUCTSHOPHISTORY
(
  HISTORYID    NUMBER(30),
  PRODUCTCODE  VARCHAR2(50 BYTE),
  DEPDATE      DATE,
  LANDPRICE    NUMBER(18,2),
  SEQ          NUMBER(9),
  AIRFROMCITY  VARCHAR2(3 BYTE),
  AIRPRICE     NUMBER(18,2),
  AIRPRICETAX  NUMBER(18,2),
  AIRLINECODE  VARCHAR2(3 BYTE),
  AIRCLASS     VARCHAR2(10 BYTE),
  ACTIVE       VARCHAR2(1 BYTE),
  DATESTAMP    DATE,
  BRANDID      VARCHAR2(5 BYTE),
  SESSID       VARCHAR2(50 BYTE)
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
