SET DEFINE OFF;
CREATE TABLE L_PRODUCTDETAIL
(
  REFERENCENUMBER  NUMBER(38),
  PRODUCTCODE      VARCHAR2(50 BYTE),
  SEQ              NUMBER(4),
  ISEQ             NUMBER(4),
  RECTYPE          VARCHAR2(1 BYTE),
  ITEMROLE         VARCHAR2(10 BYTE),
  SUPPLIERID       VARCHAR2(50 BYTE),
  SERVICEID        VARCHAR2(50 BYTE),
  DESCRIPTION      VARCHAR2(300 BYTE),
  FROMDATE         DATE,
  TODATE           DATE,
  WEEKDAYS         VARCHAR2(10 BYTE),
  ONDAY            VARCHAR2(3 BYTE),
  ONTIME           VARCHAR2(5 BYTE),
  DURATION         NUMBER(4),
  FLEXDURATION     VARCHAR2(1 BYTE),
  MINNTS           NUMBER(4),
  LINKCODE         VARCHAR2(20 BYTE),
  AUTOSELECT       VARCHAR2(10 BYTE),
  DIVISIBLEPAX     NUMBER(4),
  INVOICEFLAG      VARCHAR2(1 BYTE),
  ADDITIONALDATA   VARCHAR2(2000 BYTE),
  WHOSTAMP         VARCHAR2(100 BYTE),
  DATESTAMP        DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
