SET DEFINE OFF;
CREATE TABLE L_RESGENERAL
(
  RESNUMBER           NUMBER(18)                NOT NULL,
  REVNUMBER           INTEGER,
  REVDATE             DATE,
  RELATEDRES          VARCHAR2(200 BYTE),
  LEADNAME            VARCHAR2(102 BYTE),
  NOPAX               INTEGER,
  COMPANYID           VARCHAR2(50 BYTE),
  BRANDID             VARCHAR2(10 BYTE),
  MARKETCODE          VARCHAR2(20 BYTE),
  RESPRODUCTCODE      VARCHAR2(500 BYTE),
  RESTOURCODE         VARCHAR2(500 BYTE),
  SELLMETHOD          VARCHAR2(10 BYTE),
  CUSTOMERID          VARCHAR2(15 BYTE),
  CUSTOMERNAME        VARCHAR2(50 BYTE),
  CUSTOMERTYPE        VARCHAR2(30 BYTE),
  CONTACTID           INTEGER,
  CONTACTNAME         VARCHAR2(102 BYTE),
  ADDRESS1            VARCHAR2(100 BYTE),
  ADDRESS2            VARCHAR2(100 BYTE),
  CITY                VARCHAR2(50 BYTE),
  STATE               VARCHAR2(20 BYTE),
  POSTALCODE          VARCHAR2(10 BYTE),
  COUNTRY             VARCHAR2(20 BYTE),
  SALUTATION          VARCHAR2(50 BYTE),
  EMAIL               VARCHAR2(50 BYTE),
  PHONE               VARCHAR2(30 BYTE),
  MOBILEPHONE         VARCHAR2(30 BYTE),
  FAX                 VARCHAR2(30 BYTE),
  AFFILIATIONID       VARCHAR2(20 BYTE),
  COMMCODE            VARCHAR2(20 BYTE),
  RESSTATUS           VARCHAR2(50 BYTE),
  DOCSTATUS           VARCHAR2(50 BYTE),
  CORRESPONDENCETYPE  VARCHAR2(10 BYTE),
  DEPDATE             DATE,
  BOOKDATE            DATE,
  BOOKEDBY            VARCHAR2(50 BYTE),
  BOOKSOURCE          VARCHAR2(50 BYTE),
  EXPIREDOPTION       DATE,
  DEPOSITAMOUNT       NUMBER(18,2),
  DEPREQUIRED         VARCHAR2(20 BYTE),
  FINALPAYMENT        DATE,
  PAYMENTGUARANTEE    VARCHAR2(80 BYTE),
  REMARK              VARCHAR2(250 BYTE),
  ADDITIONALDATA      CLOB,
  QCURRENCY           VARCHAR2(3 BYTE),
  QEXCH               FLOAT(126),
  CCPER               VARCHAR2(5 BYTE),
  ISCCBKG             VARCHAR2(5 BYTE),
  TTLFEESQUOTEPRICE   NUMBER(18,2),
  TTLFEESBASECOST     NUMBER(18,2),
  TTLTAFEEQUOTEPRICE  NUMBER(18,2),
  TTLBASECOST         NUMBER(18,2),
  TTLBASECOSTTAX      NUMBER(18,2),
  TTLBASECOSTGST      NUMBER(18,2),
  TTLBASECOSTPAID     NUMBER(18,2),
  TTLBASECOSTPAIDAIR  NUMBER(18,2),
  TTLBASECOSTBALDUE   NUMBER(18,2),
  TTLQUOTEPRICE       NUMBER(18,2),
  TTLQUOTEPRICETAX    NUMBER(18,2),
  TTLQUOTEPRICEGST    NUMBER(18,4),
  TTLQUOTECOMM        NUMBER(18,2),
  TTLQUOTENETDUE      NUMBER(18,2),
  TTLQUOTERECEIVED    NUMBER(18,2),
  TTLQUOTEBALDUE      NUMBER(18,2),
  PARENTRESNUMBER     NUMBER(12),
  WHOSTAMP            VARCHAR2(50 BYTE),
  DATESTAMP           DATE
)
LOB (ADDITIONALDATA) STORE AS (
  TABLESPACE  DTW_ADV_TABLES
  ENABLE      STORAGE IN ROW
  CHUNK       16384
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          80K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
