SET DEFINE OFF;
CREATE TABLE L_RESITINERARY
(
  RESNUMBER             NUMBER(18)              NOT NULL,
  SERVICESEQ            NUMBER(18)              NOT NULL,
  GROUPSEQ              INTEGER,
  PRODUCTCODE           VARCHAR2(50 BYTE),
  SEQ                   INTEGER,
  ISEQ                  INTEGER,
  ITEMROLE              VARCHAR2(10 BYTE),
  SERVICETYPE           VARCHAR2(50 BYTE),
  DELETED               VARCHAR2(1 BYTE),
  SERVICEDATE           DATE,
  ONTIME                VARCHAR2(5 BYTE),
  SERVICEDURATION       INTEGER,
  PERDURATION           VARCHAR2(1 BYTE),
  REQMASK               VARCHAR2(50 BYTE),
  MARKETCODE            VARCHAR2(20 BYTE),
  SELLMETHOD            VARCHAR2(10 BYTE),
  SUPPLIERID            VARCHAR2(50 BYTE),
  SUPPLIERNAME          VARCHAR2(255 BYTE),
  SERVICEID             VARCHAR2(50 BYTE),
  DESCRIPTION           VARCHAR2(300 BYTE),
  INVOICEFLAG           VARCHAR2(1 BYTE),
  VCHRNOTES             VARCHAR2(2000 BYTE),
  COSTCODE              VARCHAR2(300 BYTE),
  VATCODE               VARCHAR2(10 BYTE),
  COSTDETAIL            VARCHAR2(2000 BYTE),
  ITINDESCRIPTION       VARCHAR2(1000 BYTE),
  VCHRTYPE              VARCHAR2(10 BYTE),
  TOURCODE              VARCHAR2(100 BYTE),
  MANIFESTCODE          VARCHAR2(50 BYTE),
  CONTRACTTHRU          VARCHAR2(20 BYTE),
  COMMTIMING            VARCHAR2(3 BYTE),
  BLOCKTYPE             VARCHAR2(3 BYTE),
  BLOCKCODE             VARCHAR2(50 BYTE),
  INVENTORYMAP          VARCHAR2(50 BYTE),
  CONFSTATUS            VARCHAR2(6 BYTE),
  CONFDATE              DATE,
  CONFINFO              VARCHAR2(1024 BYTE),
  SHAREWITH             VARCHAR2(50 BYTE),
  DESTINATION           VARCHAR2(3 BYTE),
  TODESTINATION         VARCHAR2(3 BYTE),
  LOCATIONCODE          VARCHAR2(180 BYTE),
  SERVICEORDER          INTEGER,
  FREENT                VARCHAR2(125 BYTE),
  SUPPLIERMEMO          VARCHAR2(200 BYTE),
  ADDITIONALINFO        VARCHAR2(2500 BYTE),
  ADDITIONALDATA        CLOB,
  XLRULE                VARCHAR2(1500 BYTE),
  COSTCURR              VARCHAR2(3 BYTE),
  COSTEXCH              NUMBER(18,6),
  QTY                   INTEGER,
  IX                    VARCHAR2(2 BYTE),
  DESIG                 VARCHAR2(75 BYTE),
  MASK                  VARCHAR2(50 BYTE),
  LOCALCOST             NUMBER(18,2),
  LOCALCOSTTAX          NUMBER(18,2),
  LOCALCOSTGST          NUMBER(18,2),
  QUOTEPRICE            NUMBER(18,2),
  QUOTEDISPLAYPRICE     NUMBER(18,2),
  QUOTEPRICETAX         NUMBER(18,2),
  QUOTEPRICEGST         NUMBER(18,4),
  QUOTEPRICENC          NUMBER(18,2),
  COMMPER               NUMBER(18,4),
  MAXCOMM               NUMBER(18,2),
  SUPPLIERCOMMFORM      VARCHAR2(200 BYTE),
  LOCALSUPPLIERCOMM     NUMBER(18,2),
  LOCALSUPPLIERCOMMREC  NUMBER(18,2),
  ROOMSASSIGNED         VARCHAR2(500 BYTE),
  DATAPRIORTOCHANGE     VARCHAR2(2000 BYTE),
  SUPPLIERREPORTED      VARCHAR2(6 BYTE),
  SUPPLIERREPORTEDDATE  DATE,
  NEEDTOREPORT          VARCHAR2(3 BYTE),
  PAIDTOSUPP            VARCHAR2(250 BYTE),
  CREATEDBY             VARCHAR2(50 BYTE),
  CREATEDDATE           DATE,
  WHOSTAMP              VARCHAR2(50 BYTE),
  DATESTAMP             DATE
)
LOB (ADDITIONALDATA) STORE AS (
  TABLESPACE  DTW_ADV_TABLES
  ENABLE      STORAGE IN ROW
  CHUNK       16384
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          80K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
