SET DEFINE OFF;
CREATE TABLE L_SUPPLIERSERVICES
(
  SUPPLIERID       VARCHAR2(50 BYTE),
  SERVICEID        VARCHAR2(50 BYTE),
  SERVICETYPE      VARCHAR2(4 BYTE),
  SERVICESTATUS    VARCHAR2(30 BYTE),
  DESCRIPTION      VARCHAR2(300 BYTE),
  VCHRNOTES        VARCHAR2(2500 BYTE),
  ITINDESCRIPTION  VARCHAR2(1000 BYTE),
  FROMDATE         DATE,
  TODATE           DATE,
  OPDAYS           VARCHAR2(20 BYTE),
  VCHRTYPE         VARCHAR2(10 BYTE),
  MANIFESTCODE     VARCHAR2(10 BYTE),
  CURRENCY         VARCHAR2(3 BYTE),
  BLOCKTYPE        VARCHAR2(3 BYTE),
  COMMTIMING       VARCHAR2(3 BYTE),
  BLOCKCODE        VARCHAR2(50 BYTE),
  MAXCHILDAGE      NUMBER(4),
  DESTINATION      VARCHAR2(3 BYTE),
  TODESTINATION    VARCHAR2(3 BYTE),
  CONTRACTTHRU     VARCHAR2(50 BYTE),
  LOCATIONCODE     VARCHAR2(90 BYTE),
  DURATION         NUMBER(12),
  MINDUR           NUMBER(12),
  MAXDUR           NUMBER(12),
  PERROOMPRICE     VARCHAR2(1 BYTE),
  PERDURATION      VARCHAR2(1 BYTE),
  FIRSTNTRATE      VARCHAR2(1 BYTE),
  PER24HRS         VARCHAR2(1 BYTE),
  DESIG1           VARCHAR2(40 BYTE),
  MASK1            VARCHAR2(80 BYTE),
  IX1              VARCHAR2(50 BYTE),
  DESIG2           VARCHAR2(40 BYTE),
  MASK2            VARCHAR2(80 BYTE),
  IX2              VARCHAR2(50 BYTE),
  DESIG3           VARCHAR2(40 BYTE),
  MASK3            VARCHAR2(80 BYTE),
  IX3              VARCHAR2(50 BYTE),
  DESIG4           VARCHAR2(40 BYTE),
  MASK4            VARCHAR2(80 BYTE),
  IX4              VARCHAR2(50 BYTE),
  DESIG5           VARCHAR2(40 BYTE),
  MASK5            VARCHAR2(80 BYTE),
  IX5              VARCHAR2(50 BYTE),
  DESIG6           VARCHAR2(40 BYTE),
  MASK6            VARCHAR2(80 BYTE),
  IX6              VARCHAR2(50 BYTE),
  DESIG7           VARCHAR2(40 BYTE),
  MASK7            VARCHAR2(80 BYTE),
  IX7              VARCHAR2(50 BYTE),
  DESIG8           VARCHAR2(40 BYTE),
  MASK8            VARCHAR2(80 BYTE),
  IX8              VARCHAR2(50 BYTE),
  FROMRESTRICTION  NUMBER(4),
  TORESTRICTION    NUMBER(4),
  DIVISIBLE        VARCHAR2(1 BYTE),
  WHOSTAMP         VARCHAR2(50 BYTE),
  DATESTAMP        DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
