SET DEFINE OFF;
CREATE TABLE L_USERS
(
  USERID           VARCHAR2(15 BYTE),
  USERNAME         VARCHAR2(30 BYTE),
  USER_PASSWORD    VARCHAR2(30 BYTE),
  EMAIL            VARCHAR2(80 BYTE),
  ADDRESS1         VARCHAR2(50 BYTE),
  ADDRESS2         VARCHAR2(50 BYTE),
  CITY             VARCHAR2(30 BYTE),
  STATE            VARCHAR2(20 BYTE),
  ZIP              VARCHAR2(10 BYTE),
  PHONE            VARCHAR2(20 BYTE),
  MOBILE_PHONE     VARCHAR2(100 BYTE),
  PHONEEXT         VARCHAR2(20 BYTE),
  BIRTHDATE        DATE,
  SSNUM            VARCHAR2(20 BYTE),
  HIREDATE         DATE,
  TERMINATIONDATE  DATE,
  USERHOURSORIG    NUMBER(10),
  USERHOURSUSED    NUMBER(10),
  SALARYTYPE       VARCHAR2(3 BYTE),
  DEPARTMENT       VARCHAR2(20 BYTE),
  USERACTIVE       VARCHAR2(50 BYTE),
  DEFAULTBRAND     VARCHAR2(15 BYTE),
  USER_COMMENT     VARCHAR2(250 BYTE),
  SUBSYSTEMS       VARCHAR2(300 BYTE),
  BRANDS           VARCHAR2(300 BYTE),
  USER_PROFILE     VARCHAR2(20 BYTE),
  CODES            CLOB,
  WHOSTAMP         VARCHAR2(200 BYTE),
  DATESTAMP        DATE
)
LOB (CODES) STORE AS (
  TABLESPACE  DTW_ADV_TABLES
  ENABLE      STORAGE IN ROW
  CHUNK       16384
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          80K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
