SET DEFINE OFF;
CREATE TABLE R_BKPAX_REJ_REC
(
  RES_NUMBER       NUMBER(18)                   NOT NULL,
  CONTACT_ID       INTEGER                      NOT NULL,
  PASSENGER_SEQ    INTEGER                      NOT NULL,
  ROOM_NUMBER      INTEGER,
  RECEIVED_AMOUNT  NUMBER(18,2),
  WHOSTAMP         VARCHAR2(50 BYTE),
  DATESTAMP        DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
