SET DEFINE OFF;
CREATE TABLE R_BRAND_REJ_REC
(
  BRAND_ID          VARCHAR2(10 BYTE),
  BRAND_NAME        VARCHAR2(50 BYTE),
  SELLING_METHODS   VARCHAR2(500 BYTE),
  FMMARKET          VARCHAR2(10 BYTE),
  QCURRENCY         VARCHAR2(20 BYTE),
  CREATED_BY        VARCHAR2(50 BYTE),
  CREATED_DATETIME  DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
