SET DEFINE OFF;
CREATE TABLE R_CUST_REJ_REC
(
  CUSTOMER_ID           VARCHAR2(15 BYTE),
  ADDRESSID             NUMBER(12),
  COMPANY_NAME          VARCHAR2(100 BYTE),
  CUSTOMER_TYPE         VARCHAR2(50 BYTE),
  MRKCUSTOMERS_PROFILE  VARCHAR2(50 BYTE),
  MRKCUSTOMERS_COMMENT  VARCHAR2(1000 BYTE),
  DEFAULTBRAND          VARCHAR2(10 BYTE),
  TAXID                 VARCHAR2(20 BYTE),
  GSTPER                VARCHAR2(10 BYTE),
  QCURRENCY             VARCHAR2(3 BYTE),
  PHONE                 VARCHAR2(30 BYTE),
  MOBILE_PHONE          VARCHAR2(30 BYTE),
  FAX                   VARCHAR2(30 BYTE),
  EMAIL                 VARCHAR2(50 BYTE),
  TERRITORY             VARCHAR2(50 BYTE),
  STATUS                VARCHAR2(10 BYTE),
  ORIGIN                VARCHAR2(255 BYTE),
  AFFILIATION_ID        VARCHAR2(20 BYTE),
  COMM_CODE             VARCHAR2(20 BYTE),
  COMM_PAYPER           VARCHAR2(10 BYTE),
  LAST_BROCHURES        VARCHAR2(250 BYTE),
  CREDIT_STATUS         VARCHAR2(40 BYTE),
  CREATED_BY            VARCHAR2(30 BYTE),
  CREATED_DATE          DATE,
  WHOSTAMP              VARCHAR2(50 BYTE),
  DATESTAMP             DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
