SET DEFINE OFF;
CREATE TABLE R_FPROD_REJ_REC
(
  PRODUCT_CODE      VARCHAR2(50 BYTE),
  PRODUCT_NAME      VARCHAR2(250 BYTE),
  DESCRIPTION       VARCHAR2(1024 BYTE),
  PRODUCT_STATUS    VARCHAR2(30 BYTE),
  BEGIN_DATE        DATE,
  END_DATE          DATE,
  BEGIN_BOOK_DATE   DATE,
  END_BOOK_DATE     DATE,
  DEFAULT_MARKET    VARCHAR2(20 BYTE),
  PRODUCT_TYPE      VARCHAR2(3 BYTE),
  ACTIVE_PAX_RANGE  VARCHAR2(10 BYTE),
  PAX_RANGE_FROM    NUMBER,
  PAX_RANGE_TO      NUMBER,
  ADULT_PRICE       NUMBER,
  ADULT_TAX         NUMBER,
  AIR_ADULT_ALLOW   NUMBER,
  LAND_COST         NUMBER,
  AIR_COST          NUMBER,
  FUEL_SURCHARGE    VARCHAR2(1000 BYTE),
  AIR_TAX           VARCHAR2(1000 BYTE),
  MASK              VARCHAR2(20 BYTE)
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
