SET DEFINE OFF;
CREATE TABLE R_PRDPRC_REJ_REC
(
  PRODUCT_CODE           VARCHAR2(50 BYTE)      NOT NULL,
  PROD_CODE_SEQ          INTEGER                NOT NULL,
  BRAND_ID               VARCHAR2(100 BYTE),
  SELL_METHOD            VARCHAR2(20 BYTE),
  QCURRENCY              VARCHAR2(3 BYTE),
  SUPPLIER_ID            VARCHAR2(50 BYTE),
  SERVICE_ID             VARCHAR2(50 BYTE),
  SALE_STATUS            VARCHAR2(20 BYTE),
  MATCH_REQ_MASK         VARCHAR2(1 BYTE),
  MASK                   VARCHAR2(20 BYTE),
  PAX_RANGE_LABEL        VARCHAR2(10 BYTE),
  PAX_RANGE_FROM         NUMBER,
  PAX_RANGE_TO           NUMBER,
  DURATION               INTEGER,
  BEGIN_DATE             DATE,
  END_DATE               DATE,
  BEGIN_BOOK_DATE        DATE,
  END_BOOK_DATE          DATE,
  WEEKDAY                VARCHAR2(7 BYTE),
  FP_TYPE                VARCHAR2(50 BYTE),
  USE_DURATION           CHAR(1 BYTE),
  FROM_ADULT_PRICE       NUMBER(18,2),
  TO_ADULT_PRICE         NUMBER(18,2),
  ADULT_PRICE            NUMBER(18,2),
  ADULT_TAX              NUMBER(18,2),
  ADULT_GST              NUMBER(18,2),
  CHILD_PRICE            NUMBER(18,2),
  CHILD_TAX              NUMBER(18,2),
  CHILD_GST              NUMBER(18,2),
  ADD_PAX_PRICE          NUMBER(18,2),
  AIR_ADULT_ALLOW        NUMBER(18,2),
  AIR_CHILD_ALLOW        NUMBER(18,2),
  INNER_AIR_ADULT_ALLOW  NUMBER(18,2),
  INNER_AIR_CHILD_ALLOW  NUMBER(18,2),
  LAND_COST              NUMBER(18,2),
  AIR_COST               NUMBER(18,2),
  DISPLAY_STATUS         VARCHAR2(20 BYTE),
  FUEL_SURCHARGE         VARCHAR2(1000 BYTE),
  AIR_TAX                VARCHAR2(1000 BYTE),
  WHOSTAMP               VARCHAR2(50 BYTE),
  DATESTAMP              DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
