SET DEFINE OFF;
CREATE TABLE R_SUPPL_REJ_REC
(
  SUPPLIER_ID          VARCHAR2(50 BYTE),
  SUPPLIER_NAME        VARCHAR2(255 BYTE),
  DOC_ADDRESS1         VARCHAR2(100 BYTE),
  DOC_ADDRESS2         VARCHAR2(100 BYTE),
  DOC_ADDRESS3         VARCHAR2(100 BYTE),
  DOC_COUNTRY          VARCHAR2(20 BYTE),
  BILL_ADDRESS1        VARCHAR2(100 BYTE),
  BILL_ADDRESS2        VARCHAR2(100 BYTE),
  BILL_ADDRESS3        VARCHAR2(100 BYTE),
  BILL_COUNTRY         VARCHAR2(20 BYTE),
  DOC_CONTACT          VARCHAR2(255 BYTE),
  DOC_PHONE            VARCHAR2(30 BYTE),
  DOC_FAX              VARCHAR2(30 BYTE),
  DOC_EMAIL            VARCHAR2(100 BYTE),
  DOC_EMERGENCY_PHONE  VARCHAR2(30 BYTE),
  CONTRACT_THRU        VARCHAR2(20 BYTE),
  PAY_CURRENCY         VARCHAR2(3 BYTE),
  COMM_METHOD          VARCHAR2(40 BYTE),
  SUPPLIER_RATING      VARCHAR2(20 BYTE),
  LOCATION_ZONE        VARCHAR2(500 BYTE),
  LOCATION_GROUP       VARCHAR2(100 BYTE),
  WEBSITE              VARCHAR2(140 BYTE),
  BILL_INFO            VARCHAR2(250 BYTE),
  OPS_CONTACT          VARCHAR2(255 BYTE),
  OPS_PHONE            VARCHAR2(30 BYTE),
  OPS_FAX              VARCHAR2(30 BYTE),
  OPS_EMAIL            VARCHAR2(80 BYTE),
  TOUR_CONTACT         VARCHAR2(255 BYTE),
  TOUR_PHONE           VARCHAR2(30 BYTE),
  TOUR_FAX             VARCHAR2(30 BYTE),
  TOUR_EMAIL           VARCHAR2(80 BYTE),
  GROUP_CONTACT        VARCHAR2(255 BYTE),
  GROUP_PHONE          VARCHAR2(30 BYTE),
  GROUP_FAX            VARCHAR2(30 BYTE),
  GROUP_EMAIL          VARCHAR2(80 BYTE),
  ACC_CONTACT          VARCHAR2(255 BYTE),
  ACC_PHONE            VARCHAR2(30 BYTE),
  ACC_FAX              VARCHAR2(30 BYTE),
  ACC_EMAIL            VARCHAR2(80 BYTE),
  CONTRACT_CONTACT     VARCHAR2(255 BYTE),
  CONTRACT_PHONE       VARCHAR2(30 BYTE),
  CONTRACT_FAX         VARCHAR2(30 BYTE),
  CONTRACT_EMAIL       VARCHAR2(80 BYTE),
  EMERGENCY_PHONE      VARCHAR2(30 BYTE),
  PREPAY               VARCHAR2(6 BYTE),
  TAXID                VARCHAR2(20 BYTE),
  SUPPLIER_TYPE        VARCHAR2(10 BYTE),
  BILLNAME             VARCHAR2(255 BYTE),
  DEFAULTGL            VARCHAR2(20 BYTE),
  TAX_CERT_NUM         VARCHAR2(20 BYTE),
  TAX_CERT_EXP         DATE,
  PAY_TYPE             VARCHAR2(1 BYTE),
  WHOSTAMP             VARCHAR2(50 BYTE),
  DATESTAMP            DATE
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
