SET DEFINE OFF;
CREATE TABLE ST_BOOK_ACT_TFILL
(
  BOOKING_PRODUCT_CODE  VARCHAR2(50 BYTE),
  DEPARTURE_DATE        DATE,
  ACTUAL_REV            NUMBER,
  ACTUAL_COST           NUMBER,
  ACTUAL_COMMISSION     NUMBER,
  ACTUAL_PAX            NUMBER
)
TABLESPACE DTW_ADV_TABLES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
